title: Xiangbo Xiong's Homepage
page-top-title: Xiangbo Xiong
top-section-bg-text: Data Science
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Xiangbo Xiong 2023-2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/xiangbo-xiong
license-link:
  text: License
  href: https://github.com/xiangbo-xiong/xiangbo-xiong.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Xiangbo Xiong&ensp;|&ensp;熊相波
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
